[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[runner]
fastReruns = true

[logger]
level = "error" 